// alert("Never Gonna Give You Up");

console.log( "Running class # 7th");

// post-increment  
// let num1 = 0;
// num1 = num1 +1;
// num1++;

// num1 = num1 +1;
// num1++;
// num1 = num1 +1 -1;

// console.log(num1);


// post decrement


// let num2 = 10;
// num2 = num2 -1;
// num2 = num2 -5;
// console.log( "num2" , num2)

// The Bodmas rule follows the order of the BODMAS acronym ie 
// B – Brackets, O – Order of powers or roots, D – Division, 
// M – Multiplication A – Addition, and S – Subtraction. Mathematical 
// expressions with multiple operators need to be solved from left to 
// right in the order of BODMAS.

// let math = 30 / 5 + 3;
// console.log(math)

// let math = 30 / (5 + 3);
// console.log(math)
// let userName = "Tahira ";
// console.log("Welcome:", userName)

// let userName = "Tahira ";
// console.log("Welcome" + " " +userName+ "how are you" )

// var name = "Riaz";

// let field = "programing";
//  field = "Docter";
 
// let name = "Tahira";
// let fingers = 10;
// let priceOfEgg = 25;
 
// console.log( name + " " + fingers + " " + priceOfEgg);

// Prompts

let userName = prompt("What is your name");
 console.log("Welcome" + " "+ userName);


let operator = prompt("write your opertor");
console.log( 1 + 2 );



